### ISSUE TITLE
Crashing on Windows 10 vm

### ISSUE THREAD

**Issue by mor619dx** [asamy/ksm#1]
Hey,

I'm trying to run the project (compiled using vs2015 since I couldn't make it compile on mingw using the Makefile for some reason)

And I tried to run it on vm (VMWare) on windows 10 x64 with hyper-v on (complained the first time it wasn't installed)

and I get BSOD, opening the dump in Windbg shows the crash is in the function ept_check_capabilitiy

on the line of u64 vpid = __readmsr(MSR_IA32_VMX_EPT_VPID_CAP);

I don't think it has to do with the fact I compiled with vs2015 instead of gcc.

Any idea how to solve it?
and also it will help a lot if you could write which version of mingw your using so i would be sure the version isn't the problem of compiling.

Thank you for your help!

**Comment by asamy** [comment]
Hi,

The MinGW Makefile is broken and is not even tested, so ignore it.  I use VS 2015 too.
If the rdmsr is causing #GP then that could be mean your processor does not support it.  What's your processor?

I am not sure about Windows Hyper-V, I have not tested it under it myself, so you might want to try disabling it, maybe it's failing at emulating EPT or something, I don't know.

**Comment by mor619dx** [comment]
Ok i fixed it by enabling VT-x: processors -> Virtualize VT-x (in VMWare)

Howevery when I try to start the service (after creating it) it failed when calling STATIC_DPC_RET in the bottom of ksm_init function.

running: sc start ksm

returning the following error:

```
[SC] StartService FAILED 31:

A device attached to the system is not functioning.
```

How did you run your service and did you use vm or did you run it on non vm machine?

**Comment by asamy** [comment]
If it's failing at that point (STATIC_DPC_RET() from ksm_init I presume), then it could be due to vcpu_init failing in setup_vmcs(), that's the most troublesome function of them, so you might want to singlestep it to figure out the cause.

About the service: I did both, however, sometimes VMware wouldn't like the EPT features I am requesting so it will not work at all (don't quite remember what machine specs, but I recall the CPU did support the features and I had ran it under native anyway).

This is what I use for VMware: ![img](http://i.imgur.com/2OD3cUf.png)

**Comment by mor619dx** [comment]
Tried to play with all the options but couldn't make it really work on vmware vm.

So I run it on a physical computer without VMWare and it works,

Thanks for your help :)

**Comment by asamy** [comment]
Hi,

It now compiles under MinGW.  Also added backward compatibility so you can test on VMs.

Cheers.
